/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "7Wate",
  "tagline": "For Freedom",
  "url": "https://qq1120637483.github.io/",
  "baseUrl": "/",
  "onBrokenLinks": "log",
  "onBrokenMarkdownLinks": "log",
  "favicon": "img/favicon.ico",
  "projectName": "qq1120637483.github.io",
  "organizationName": "qq1120637483",
  "trailingSlash": false,
  "deploymentBranch": "gh-pages",
  "i18n": {
    "defaultLocale": "zh-Hans",
    "locales": [
      "zh-Hans"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "presets": [
    [
      "classic",
      {
        "docs": {
          "sidebarPath": "G:\\Docusaurus折腾\\7Wate\\wiki\\sidebars.js",
          "editUrl": "https://git.7wate.com/zhouzhongping/wiki/src/branch/master",
          "showLastUpdateAuthor": true,
          "showLastUpdateTime": true,
          "breadcrumbs": false
        },
        "blog": {
          "blogTitle": "7Wate`s Blog",
          "blogDescription": "7Wate 的个人生活和工作记录",
          "blogSidebarCount": 10,
          "blogSidebarTitle": "近期文章",
          "showReadingTime": true,
          "editUrl": "https://git.7wate.com/zhouzhongping/wiki/src/branch/master",
          "feedOptions": {
            "title": "7Wate`s Blog",
            "description": "7Wate 的个人生活和工作记录",
            "type": "all",
            "copyright": "Copyright © 2022 7Wate, Inc."
          }
        },
        "theme": {
          "customCss": "G:\\Docusaurus折腾\\7Wate\\wiki\\src\\css\\custom.css"
        },
        "sitemap": {
          "changefreq": "weekly",
          "priority": 0.5,
          "filename": "sitemap.xml"
        },
        "googleAnalytics": {
          "trackingID": "G-MHMEL0F832",
          "anonymizeIP": true
        },
        "gtag": {
          "trackingID": "G-MHMEL0F832",
          "anonymizeIP": true
        }
      }
    ]
  ],
  "plugins": [
    [
      "@docusaurus/plugin-content-docs",
      {
        "id": "structures-algorithms",
        "path": "wiki/structures-algorithms",
        "routeBasePath": "structures-algorithms",
        "sidebarPath": "G:\\Docusaurus折腾\\7Wate\\wiki\\sidebars.js",
        "editUrl": "https://git.7wate.com/zhouzhongping/wiki/src/branch/master",
        "showLastUpdateAuthor": true,
        "showLastUpdateTime": true,
        "breadcrumbs": false
      }
    ],
    [
      "@docusaurus/plugin-content-docs",
      {
        "id": "computer-network",
        "path": "wiki/computer-network",
        "routeBasePath": "computer-network",
        "sidebarPath": "G:\\Docusaurus折腾\\7Wate\\wiki\\sidebars.js",
        "editUrl": "https://git.7wate.com/zhouzhongping/wiki/src/branch/master",
        "showLastUpdateAuthor": true,
        "showLastUpdateTime": true,
        "breadcrumbs": false
      }
    ],
    [
      "@docusaurus/plugin-content-docs",
      {
        "id": "operating-system",
        "path": "wiki/operating-system",
        "routeBasePath": "operating-system",
        "sidebarPath": "G:\\Docusaurus折腾\\7Wate\\wiki\\sidebars.js",
        "editUrl": "https://git.7wate.com/zhouzhongping/wiki/src/branch/master",
        "showLastUpdateAuthor": true,
        "showLastUpdateTime": true,
        "breadcrumbs": false
      }
    ],
    [
      "@docusaurus/plugin-content-docs",
      {
        "id": "database-system",
        "path": "wiki/database-system",
        "routeBasePath": "database-system",
        "sidebarPath": "G:\\Docusaurus折腾\\7Wate\\wiki\\sidebars.js",
        "editUrl": "https://git.7wate.com/zhouzhongping/wiki/src/branch/master",
        "showLastUpdateAuthor": true,
        "showLastUpdateTime": true,
        "breadcrumbs": false
      }
    ],
    [
      "@docusaurus/plugin-content-docs",
      {
        "id": "computer-security",
        "path": "wiki/computer-security",
        "routeBasePath": "computer-security",
        "sidebarPath": "G:\\Docusaurus折腾\\7Wate\\wiki\\sidebars.js",
        "editUrl": "https://git.7wate.com/zhouzhongping/wiki/src/branch/master",
        "showLastUpdateAuthor": true,
        "showLastUpdateTime": true,
        "breadcrumbs": false
      }
    ],
    [
      "@docusaurus/plugin-content-docs",
      {
        "id": "software-engineering",
        "path": "wiki/software-engineering",
        "routeBasePath": "software-engineering",
        "sidebarPath": "G:\\Docusaurus折腾\\7Wate\\wiki\\sidebars.js",
        "editUrl": "https://git.7wate.com/zhouzhongping/wiki/src/branch/master",
        "showLastUpdateAuthor": true,
        "showLastUpdateTime": true,
        "breadcrumbs": false
      }
    ],
    [
      "@docusaurus/plugin-content-docs",
      {
        "id": "org",
        "path": "group/organization",
        "routeBasePath": "org",
        "sidebarPath": "G:\\Docusaurus折腾\\7Wate\\wiki\\sidebars.js",
        "editUrl": "https://git.7wate.com/zhouzhongping/wiki/src/branch/master",
        "showLastUpdateAuthor": true,
        "showLastUpdateTime": true,
        "breadcrumbs": false
      }
    ],
    [
      "@docusaurus/plugin-content-docs",
      {
        "id": "roadmap",
        "path": "work/roadmap",
        "routeBasePath": "roadmap",
        "sidebarPath": "G:\\Docusaurus折腾\\7Wate\\wiki\\sidebars.js",
        "editUrl": "https://git.7wate.com/zhouzhongping/wiki/src/branch/master",
        "showLastUpdateAuthor": true,
        "showLastUpdateTime": true,
        "breadcrumbs": false
      }
    ],
    [
      "@docusaurus/plugin-content-docs",
      {
        "id": "life",
        "path": "life",
        "routeBasePath": "life",
        "sidebarPath": "G:\\Docusaurus折腾\\7Wate\\wiki\\sidebars.js",
        "editUrl": "https://git.7wate.com/zhouzhongping/wiki/src/branch/master",
        "showLastUpdateAuthor": true,
        "showLastUpdateTime": true,
        "breadcrumbs": false
      }
    ],
    [
      "@docusaurus/plugin-content-docs",
      {
        "id": "journal",
        "path": "journal",
        "routeBasePath": "journal",
        "sidebarPath": "G:\\Docusaurus折腾\\7Wate\\wiki\\sidebars.js",
        "editUrl": "https://git.7wate.com/zhouzhongping/wiki/src/branch/master",
        "showLastUpdateAuthor": true,
        "showLastUpdateTime": true,
        "breadcrumbs": false
      }
    ]
  ],
  "themeConfig": {
    "docs": {
      "sidebar": {
        "hideable": true,
        "autoCollapseCategories": false
      },
      "versionPersistence": "localStorage"
    },
    "metadata": [
      {
        "name": "keywords",
        "content": "7wate, wiki, blog, c, c++, java, python, linux"
      }
    ],
    "navbar": {
      "title": "🐋 Faith&Passion's Wiki",
      "hideOnScroll": true,
      "items": [
        {
          "to": "/blog",
          "label": "🍁 博客",
          "position": "right"
        },
        {
          "position": "right",
          "label": "🦖 Wiki",
          "items": [
            {
              "label": "数据结构与算法",
              "to": "/structures-algorithms"
            },
            {
              "label": "计算机网络",
              "to": "/computer-network"
            },
            {
              "label": "操作系统",
              "to": "/operating-system"
            },
            {
              "label": "数据库",
              "to": "/database-system"
            },
            {
              "label": "网络安全",
              "to": "/computer-security"
            },
            {
              "label": "软件工程",
              "to": "/software-engineering"
            }
          ]
        },
        {
          "position": "right",
          "label": "🪟 面经",
          "items": [
            {
              "label": "前端面经",
              "to": "/roadmap"
            }
          ]
        },
        {
          "position": "right",
          "label": "⏰ LeetCode",
          "items": [
            {
              "label": "开源社区",
              "to": "/org"
            }
          ]
        },
        {
          "to": "/life",
          "label": "🏄‍♂️ 生活",
          "position": "right"
        },
        {
          "to": "/journal",
          "label": "📜 随笔日记",
          "position": "right"
        }
      ]
    },
    "footer": {
      "style": "dark",
      "copyright": "Copyright © 2022 7Wate, Inc. Built with <a href=\"https://www.docusaurus.cn/\" target=\"_blank\" rel=\"noopener noreferrer\">Docusaurus</a>.<br>Powered by <a href=\"https://webify.cloudbase.net/\" target=\"_blank\" rel=\"noopener noreferrer\">CloudBase Webify</a>",
      "links": []
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "defaultLanguage": "markdown",
      "additionalLanguages": [
        "java",
        "git",
        "nginx",
        "http"
      ],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": false
    },
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "baseUrlIssueBanner": true,
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "themes": [],
  "scripts": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false
};
