name: BlogCI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Download Source file
      uses: actions/checkout@v2
      with:
        ref: dev # 此处修改为自己存放 Hexo 源文件的分支

    - name: Prepare Node env
      uses: actions/setup-node@v1
      with:
        node-version: "14.17.0" # 此处和自己的nodejs版本对应(10,12测试成功)

    - name: Set Env
      env: 
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}  
      run: |
        git config --global user.name 'qq1120637483' # github用户名
        git config --global user.email '1120637483@qq.com' # github邮箱
        sed -i "s/ACCESS_TOKEN/$ACCESS_TOKEN/g" ./_config.yml
    - name: Hexo
      run: |
        npm install hexo
        npm install
        npx hexo clean
        npx hexo g -d

    - name: testDev
      run: |
        git branch -a